baseurl = "https://poorimpulse.co"
languageCode = "en-us"
title = "Poor Impulse"
theme = "pic3"

[permalinks]
  podcast = ":section/:slug"

[taxonomies]
  season = "seasons"
  tag = "tags"

[author]
  name = "Russell Hay"

[params]
  itunes_link = "https://itunes.apple.com/us/podcast/poor-impulse"
  patreon_link = "http://patreon.com/poorimpulse"
  circle_portrait_size = 250

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["txt"]

[outputFormats]
  [outputFormats.TEXT]
    isPlainText = true
    mediaType = "text/plain"
    baseName = "transcript"

[outputs]
  home = [ "HTML", "AMP", "RSS"]
  page = [ "HTML", "TEXT" ]
  section = ["HTML" ]

# [[menu.main]]
#   name = "supporters"
#   identifier = "supporters"
#   url = "/supporters"

# [[menu.main]]
#   name = "contributors"
#   identifier = "contributors"
#   url = "/contributors"

[[menu.main]]
  name = "donate"
  identifier = "donate"
  url = "/donate"
  weight = 10

[[menu.main]]
  name = "about"
  identifier = "about"
  url = "/about"
  weight = 1

[[menu.main]]
  name = "üè†"
  identifier = "home"
  url = "/"
  weight = -9999

[[menu.main]]
  name = "üì°"
  identifier = "subscribe"
  url = "/index.xml"
  weight = 100

[[menu.main]]
  name = "üçé"
  identifier = "itunes"
  url = "/itunes"
  weight = 100